[package]
org = "busis"
name = "payment_service"
version = "0.1.0"
distribution = "2201.13.5"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "mysql"
version = "1.13.1"

[[dependency]]
org = "ballerinax"
name = "mysql.driver"
version = "1.8.0"

[[dependency]]
org = "ballerinax"
name = "kafka"
version = "3.5.0"
